---
title: 'Binary CFA'
# descriotion:
vignette: >
  %\VignetteIndexEntry{Binary CFA}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
knitr:
  opts_chunk: 
    collapse: true
    comment: '#>'
---

As of version 0.2.1.9000, `{INLAvaan}` supports the fitting of binary data for CFA using the pairwise likelihood function available from `{lavaan}`. 
This is an experimental feature which needs further research and testing.
Some notes:

- Using PML is considered a "limited-information" approach, due to pairwise likelihood contributions not utilising the fully joint information in the data.
- The scale of the PML function will significantly be different, since the total pairwise log-likelihood adds up contributions in pairs. Following the literature on spatial models using composite likelihoods, `{INLAvaan}` adjusts this by a factor of $1/\sqrt{p}$.
- It is proabably unwise to use the Laplace-approximated marginal likelihood for model comparison. The ppp also may not be suitable for ordinal data and needs a rethink.
- Bayesian estimation of CFA favours the `parameterization = "theta"` option, since the priors on residual variances are more intuitive to specify. `{INLAvaan}` switches to this by default.
- For binary models, normal priors for the thresholds should be fine. But looking ahead for ordinal models, the priors for thresholds should be specified in such a way that the ordering is preserved $\tau_0 < \tau_1 < \tau_2 < \cdots < \tau_k$. This is not yet implemented in `{INLAvaan}`.

Having said that, let's take a look at how binary CFA can be implemented in `{INLAvaan}`.

```{r}
library(INLAvaan)
library(blavaan)
set.seed(161)

# Generate data
n <- 250
truval <- c(0.8, 0.7, 0.6, 0.5, 0.4, -1.43, -0.55, -0.13, -0.72, -1.13)
dat <- lavaan::simulateData(
  "eta =~ 0.8*y1 + 0.7*5y2 + 0.6*y3 + 0.5*y4 + 0.4*y5
   y1 | -1.43*t1
   y2 | -0.55*t1
   y3 | -0.13*t1
   y4 | -0.72*t1
   y5 | -1.13*t1",
  ordered = TRUE,
  sample.nobs = n
)
head(dat)

# Fit INLAvaan model
mod <- "eta  =~ y1 + y2 + y3 + y4 + y5"
fit <- acfa(mod, dat, ordered = TRUE, std.lv = TRUE, estimator = "PML")
plot(fit, truth = truval)
```

