// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_mills_ratio
NumericVector cpp_mills_ratio(NumericVector u);
RcppExport SEXP _INLAvaan_cpp_mills_ratio(SEXP uSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type u(uSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_mills_ratio(u));
    return rcpp_result_gen;
END_RCPP
}
// cpp_dsnorm
NumericVector cpp_dsnorm(NumericVector x, const double xi, const double omega, const double alpha, const double logC, const bool log_out);
RcppExport SEXP _INLAvaan_cpp_dsnorm(SEXP xSEXP, SEXP xiSEXP, SEXP omegaSEXP, SEXP alphaSEXP, SEXP logCSEXP, SEXP log_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const double >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< const double >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type logC(logCSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_out(log_outSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dsnorm(x, xi, omega, alpha, logC, log_out));
    return rcpp_result_gen;
END_RCPP
}
// cpp_fit_skew_normal_objective
double cpp_fit_skew_normal_objective(NumericVector param, NumericVector x, NumericVector y, const double threshold_log_drop, const bool is_est_k, const double temp);
RcppExport SEXP _INLAvaan_cpp_fit_skew_normal_objective(SEXP paramSEXP, SEXP xSEXP, SEXP ySEXP, SEXP threshold_log_dropSEXP, SEXP is_est_kSEXP, SEXP tempSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type param(paramSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< const double >::type threshold_log_drop(threshold_log_dropSEXP);
    Rcpp::traits::input_parameter< const bool >::type is_est_k(is_est_kSEXP);
    Rcpp::traits::input_parameter< const double >::type temp(tempSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fit_skew_normal_objective(param, x, y, threshold_log_drop, is_est_k, temp));
    return rcpp_result_gen;
END_RCPP
}
// cpp_fit_skew_normal_gradient
NumericVector cpp_fit_skew_normal_gradient(NumericVector param, NumericVector x, NumericVector y, const double threshold_log_drop, const bool is_est_k, const double temp);
RcppExport SEXP _INLAvaan_cpp_fit_skew_normal_gradient(SEXP paramSEXP, SEXP xSEXP, SEXP ySEXP, SEXP threshold_log_dropSEXP, SEXP is_est_kSEXP, SEXP tempSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type param(paramSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< const double >::type threshold_log_drop(threshold_log_dropSEXP);
    Rcpp::traits::input_parameter< const bool >::type is_est_k(is_est_kSEXP);
    Rcpp::traits::input_parameter< const double >::type temp(tempSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fit_skew_normal_gradient(param, x, y, threshold_log_drop, is_est_k, temp));
    return rcpp_result_gen;
END_RCPP
}
// cpp_fit_skew_normal_hessian
NumericMatrix cpp_fit_skew_normal_hessian(NumericVector param, NumericVector x, NumericVector y, const double threshold_log_drop, const double temp);
RcppExport SEXP _INLAvaan_cpp_fit_skew_normal_hessian(SEXP paramSEXP, SEXP xSEXP, SEXP ySEXP, SEXP threshold_log_dropSEXP, SEXP tempSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type param(paramSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< const double >::type threshold_log_drop(threshold_log_dropSEXP);
    Rcpp::traits::input_parameter< const double >::type temp(tempSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fit_skew_normal_hessian(param, x, y, threshold_log_drop, temp));
    return rcpp_result_gen;
END_RCPP
}
// cpp_fit_skew_normal_optimize
List cpp_fit_skew_normal_optimize(NumericVector par0, NumericVector x, NumericVector y, const double threshold_log_drop, const bool is_est_k, const double temp, const int max_iter, const double grad_tol, const int m_bfgs, const int max_ls, const double h);
RcppExport SEXP _INLAvaan_cpp_fit_skew_normal_optimize(SEXP par0SEXP, SEXP xSEXP, SEXP ySEXP, SEXP threshold_log_dropSEXP, SEXP is_est_kSEXP, SEXP tempSEXP, SEXP max_iterSEXP, SEXP grad_tolSEXP, SEXP m_bfgsSEXP, SEXP max_lsSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type par0(par0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< const double >::type threshold_log_drop(threshold_log_dropSEXP);
    Rcpp::traits::input_parameter< const bool >::type is_est_k(is_est_kSEXP);
    Rcpp::traits::input_parameter< const double >::type temp(tempSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const double >::type grad_tol(grad_tolSEXP);
    Rcpp::traits::input_parameter< const int >::type m_bfgs(m_bfgsSEXP);
    Rcpp::traits::input_parameter< const int >::type max_ls(max_lsSEXP);
    Rcpp::traits::input_parameter< const double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fit_skew_normal_optimize(par0, x, y, threshold_log_drop, is_est_k, temp, max_iter, grad_tol, m_bfgs, max_ls, h));
    return rcpp_result_gen;
END_RCPP
}
// cpp_fit_skew_normal_sample_nll
double cpp_fit_skew_normal_sample_nll(NumericVector par, NumericVector x);
RcppExport SEXP _INLAvaan_cpp_fit_skew_normal_sample_nll(SEXP parSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type par(parSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fit_skew_normal_sample_nll(par, x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_fit_skew_normal_sample_optimize
List cpp_fit_skew_normal_sample_optimize(NumericVector par0, NumericVector x, const int max_iter, const double grad_tol, const int m_bfgs, const int max_ls, const double h);
RcppExport SEXP _INLAvaan_cpp_fit_skew_normal_sample_optimize(SEXP par0SEXP, SEXP xSEXP, SEXP max_iterSEXP, SEXP grad_tolSEXP, SEXP m_bfgsSEXP, SEXP max_lsSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type par0(par0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const double >::type grad_tol(grad_tolSEXP);
    Rcpp::traits::input_parameter< const int >::type m_bfgs(m_bfgsSEXP);
    Rcpp::traits::input_parameter< const int >::type max_ls(max_lsSEXP);
    Rcpp::traits::input_parameter< const double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fit_skew_normal_sample_optimize(par0, x, max_iter, grad_tol, m_bfgs, max_ls, h));
    return rcpp_result_gen;
END_RCPP
}
// cpp_fast_grad
NumericVector cpp_fast_grad(Function fn, NumericVector x, const double h);
RcppExport SEXP _INLAvaan_cpp_fast_grad(SEXP fnSEXP, SEXP xSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type fn(fnSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fast_grad(fn, x, h));
    return rcpp_result_gen;
END_RCPP
}
// cpp_fast_jacobian
NumericMatrix cpp_fast_jacobian(Function gr_fn, NumericVector x, const double h);
RcppExport SEXP _INLAvaan_cpp_fast_jacobian(SEXP gr_fnSEXP, SEXP xSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type gr_fn(gr_fnSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fast_jacobian(gr_fn, x, h));
    return rcpp_result_gen;
END_RCPP
}
// cpp_fast_hessian
NumericMatrix cpp_fast_hessian(Function fn, NumericVector x, const double h);
RcppExport SEXP _INLAvaan_cpp_fast_hessian(SEXP fnSEXP, SEXP xSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type fn(fnSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fast_hessian(fn, x, h));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lisrel_implied_cov
NumericMatrix cpp_lisrel_implied_cov(List model, NumericVector x_free);
RcppExport SEXP _INLAvaan_cpp_lisrel_implied_cov(SEXP modelSEXP, SEXP x_freeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_free(x_freeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lisrel_implied_cov(model, x_free));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lisrel_implied_mean
NumericMatrix cpp_lisrel_implied_mean(List model, NumericVector x_free);
RcppExport SEXP _INLAvaan_cpp_lisrel_implied_mean(SEXP modelSEXP, SEXP x_freeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_free(x_freeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lisrel_implied_mean(model, x_free));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lisrel_latent_posterior
List cpp_lisrel_latent_posterior(List model, NumericVector x_free);
RcppExport SEXP _INLAvaan_cpp_lisrel_latent_posterior(SEXP modelSEXP, SEXP x_freeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_free(x_freeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lisrel_latent_posterior(model, x_free));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lisrel_predict_y
List cpp_lisrel_predict_y(List model, NumericVector x_free, const bool add_noise);
RcppExport SEXP _INLAvaan_cpp_lisrel_predict_y(SEXP modelSEXP, SEXP x_freeSEXP, SEXP add_noiseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_free(x_freeSEXP);
    Rcpp::traits::input_parameter< const bool >::type add_noise(add_noiseSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lisrel_predict_y(model, x_free, add_noise));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lisrel_impute_missing
List cpp_lisrel_impute_missing(List model, NumericVector x_free);
RcppExport SEXP _INLAvaan_cpp_lisrel_impute_missing(SEXP modelSEXP, SEXP x_freeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_free(x_freeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lisrel_impute_missing(model, x_free));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lisrel_loglik_and_grad
List cpp_lisrel_loglik_and_grad(List model, NumericVector x_free);
RcppExport SEXP _INLAvaan_cpp_lisrel_loglik_and_grad(SEXP modelSEXP, SEXP x_freeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_free(x_freeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lisrel_loglik_and_grad(model, x_free));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lisrel_loglik
double cpp_lisrel_loglik(List model, NumericVector x_free);
RcppExport SEXP _INLAvaan_cpp_lisrel_loglik(SEXP modelSEXP, SEXP x_freeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_free(x_freeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lisrel_loglik(model, x_free));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lisrel_grad
NumericVector cpp_lisrel_grad(List model, NumericVector x_free);
RcppExport SEXP _INLAvaan_cpp_lisrel_grad(SEXP modelSEXP, SEXP x_freeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_free(x_freeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lisrel_grad(model, x_free));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lisrel_hessian_theta
NumericMatrix cpp_lisrel_hessian_theta(List model, NumericVector par, IntegerVector transforms, IntegerVector cov_var_idx1, IntegerVector cov_var_idx2, const double h_hess);
RcppExport SEXP _INLAvaan_cpp_lisrel_hessian_theta(SEXP modelSEXP, SEXP parSEXP, SEXP transformsSEXP, SEXP cov_var_idx1SEXP, SEXP cov_var_idx2SEXP, SEXP h_hessSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type par(parSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type transforms(transformsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cov_var_idx1(cov_var_idx1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cov_var_idx2(cov_var_idx2SEXP);
    Rcpp::traits::input_parameter< const double >::type h_hess(h_hessSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lisrel_hessian_theta(model, par, transforms, cov_var_idx1, cov_var_idx2, h_hess));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lisrel_twolevel_implied_blocks
List cpp_lisrel_twolevel_implied_blocks(List model, NumericVector x_free);
RcppExport SEXP _INLAvaan_cpp_lisrel_twolevel_implied_blocks(SEXP modelSEXP, SEXP x_freeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_free(x_freeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lisrel_twolevel_implied_blocks(model, x_free));
    return rcpp_result_gen;
END_RCPP
}
// cpp_marginals_batch
List cpp_marginals_batch(List model, NumericVector theta_star, NumericMatrix Vscan, NumericMatrix L_chol, IntegerVector transforms, NumericVector z_grid, IntegerVector cov_var_idx1, IntegerVector cov_var_idx2, NumericMatrix H_prior_neg, double delta_outer, double h_inner, int nthreads);
RcppExport SEXP _INLAvaan_cpp_marginals_batch(SEXP modelSEXP, SEXP theta_starSEXP, SEXP VscanSEXP, SEXP L_cholSEXP, SEXP transformsSEXP, SEXP z_gridSEXP, SEXP cov_var_idx1SEXP, SEXP cov_var_idx2SEXP, SEXP H_prior_negSEXP, SEXP delta_outerSEXP, SEXP h_innerSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta_star(theta_starSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Vscan(VscanSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type L_chol(L_cholSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type transforms(transformsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z_grid(z_gridSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cov_var_idx1(cov_var_idx1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cov_var_idx2(cov_var_idx2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type H_prior_neg(H_prior_negSEXP);
    Rcpp::traits::input_parameter< double >::type delta_outer(delta_outerSEXP);
    Rcpp::traits::input_parameter< double >::type h_inner(h_innerSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_marginals_batch(model, theta_star, Vscan, L_chol, transforms, z_grid, cov_var_idx1, cov_var_idx2, H_prior_neg, delta_outer, h_inner, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lisrel_optimize
List cpp_lisrel_optimize(List model, NumericVector par0, IntegerVector transforms, int max_iter, double grad_tol, int m_bfgs, int max_ls, double h);
RcppExport SEXP _INLAvaan_cpp_lisrel_optimize(SEXP modelSEXP, SEXP par0SEXP, SEXP transformsSEXP, SEXP max_iterSEXP, SEXP grad_tolSEXP, SEXP m_bfgsSEXP, SEXP max_lsSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type par0(par0SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type transforms(transformsSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type grad_tol(grad_tolSEXP);
    Rcpp::traits::input_parameter< int >::type m_bfgs(m_bfgsSEXP);
    Rcpp::traits::input_parameter< int >::type max_ls(max_lsSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lisrel_optimize(model, par0, transforms, max_iter, grad_tol, m_bfgs, max_ls, h));
    return rcpp_result_gen;
END_RCPP
}
// cpp_norta_adjust
NumericMatrix cpp_norta_adjust(NumericVector z1, NumericVector ww_flat, NumericMatrix q1_all, NumericMatrix R_in, NumericVector mu_sn, NumericVector sd_sn, NumericVector alphas, NumericVector u_grid, NumericMatrix q_grids, int nthreads);
RcppExport SEXP _INLAvaan_cpp_norta_adjust(SEXP z1SEXP, SEXP ww_flatSEXP, SEXP q1_allSEXP, SEXP R_inSEXP, SEXP mu_snSEXP, SEXP sd_snSEXP, SEXP alphasSEXP, SEXP u_gridSEXP, SEXP q_gridsSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type z1(z1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ww_flat(ww_flatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type q1_all(q1_allSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type R_in(R_inSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu_sn(mu_snSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sd_sn(sd_snSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alphas(alphasSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type u_grid(u_gridSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type q_grids(q_gridsSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_norta_adjust(z1, ww_flat, q1_all, R_in, mu_sn, sd_sn, alphas, u_grid, q_grids, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_sample_batch
List cpp_sample_batch(NumericMatrix z_raw, NumericMatrix R_chol_ut, NumericVector sn_xi, NumericVector sn_omega, NumericVector sn_alpha, NumericVector transforms, IntegerVector cov_var_idx1, IntegerVector cov_var_idx2, int nthreads, int n_grid);
RcppExport SEXP _INLAvaan_cpp_sample_batch(SEXP z_rawSEXP, SEXP R_chol_utSEXP, SEXP sn_xiSEXP, SEXP sn_omegaSEXP, SEXP sn_alphaSEXP, SEXP transformsSEXP, SEXP cov_var_idx1SEXP, SEXP cov_var_idx2SEXP, SEXP nthreadsSEXP, SEXP n_gridSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type z_raw(z_rawSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type R_chol_ut(R_chol_utSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sn_xi(sn_xiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sn_omega(sn_omegaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sn_alpha(sn_alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type transforms(transformsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cov_var_idx1(cov_var_idx1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cov_var_idx2(cov_var_idx2SEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< int >::type n_grid(n_gridSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_sample_batch(z_raw, R_chol_ut, sn_xi, sn_omega, sn_alpha, transforms, cov_var_idx1, cov_var_idx2, nthreads, n_grid));
    return rcpp_result_gen;
END_RCPP
}
// cpp_prior_logdens_scan
NumericMatrix cpp_prior_logdens_scan(NumericVector theta_star, NumericMatrix Vscan, NumericVector z_grid, IntegerVector free_id, IntegerVector trans_type, IntegerVector prior_type, NumericVector p1, NumericVector p2, LogicalVector is_sd_prior, LogicalVector is_prec_prior, int nthreads);
RcppExport SEXP _INLAvaan_cpp_prior_logdens_scan(SEXP theta_starSEXP, SEXP VscanSEXP, SEXP z_gridSEXP, SEXP free_idSEXP, SEXP trans_typeSEXP, SEXP prior_typeSEXP, SEXP p1SEXP, SEXP p2SEXP, SEXP is_sd_priorSEXP, SEXP is_prec_priorSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type theta_star(theta_starSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Vscan(VscanSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z_grid(z_gridSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type free_id(free_idSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type trans_type(trans_typeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type prior_type(prior_typeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p2(p2SEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type is_sd_prior(is_sd_priorSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type is_prec_prior(is_prec_priorSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_prior_logdens_scan(theta_star, Vscan, z_grid, free_id, trans_type, prior_type, p1, p2, is_sd_prior, is_prec_prior, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_prior_logdens_vec
NumericVector cpp_prior_logdens_vec(NumericMatrix theta_mat, IntegerVector free_id, IntegerVector trans_type, IntegerVector prior_type, NumericVector p1, NumericVector p2, LogicalVector is_sd_prior, LogicalVector is_prec_prior, int nthreads);
RcppExport SEXP _INLAvaan_cpp_prior_logdens_vec(SEXP theta_matSEXP, SEXP free_idSEXP, SEXP trans_typeSEXP, SEXP prior_typeSEXP, SEXP p1SEXP, SEXP p2SEXP, SEXP is_sd_priorSEXP, SEXP is_prec_priorSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type theta_mat(theta_matSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type free_id(free_idSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type trans_type(trans_typeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type prior_type(prior_typeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p2(p2SEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type is_sd_prior(is_sd_priorSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type is_prec_prior(is_prec_priorSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_prior_logdens_vec(theta_mat, free_id, trans_type, prior_type, p1, p2, is_sd_prior, is_prec_prior, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_vb_fg
List cpp_vb_fg(NumericVector delta, NumericVector mu0, NumericMatrix L, NumericMatrix Z, List model, IntegerVector transforms, IntegerVector cov_var_idx1, IntegerVector cov_var_idx2, IntegerVector prior_free_id, IntegerVector prior_trans, IntegerVector prior_type, NumericVector prior_p1, NumericVector prior_p2, LogicalVector prior_is_sd, LogicalVector prior_is_prec, NumericMatrix ceq_K, int nthreads);
RcppExport SEXP _INLAvaan_cpp_vb_fg(SEXP deltaSEXP, SEXP mu0SEXP, SEXP LSEXP, SEXP ZSEXP, SEXP modelSEXP, SEXP transformsSEXP, SEXP cov_var_idx1SEXP, SEXP cov_var_idx2SEXP, SEXP prior_free_idSEXP, SEXP prior_transSEXP, SEXP prior_typeSEXP, SEXP prior_p1SEXP, SEXP prior_p2SEXP, SEXP prior_is_sdSEXP, SEXP prior_is_precSEXP, SEXP ceq_KSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu0(mu0SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type L(LSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type transforms(transformsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cov_var_idx1(cov_var_idx1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cov_var_idx2(cov_var_idx2SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type prior_free_id(prior_free_idSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type prior_trans(prior_transSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type prior_type(prior_typeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prior_p1(prior_p1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prior_p2(prior_p2SEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type prior_is_sd(prior_is_sdSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type prior_is_prec(prior_is_precSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type ceq_K(ceq_KSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_vb_fg(delta, mu0, L, Z, model, transforms, cov_var_idx1, cov_var_idx2, prior_free_id, prior_trans, prior_type, prior_p1, prior_p2, prior_is_sd, prior_is_prec, ceq_K, nthreads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_INLAvaan_cpp_mills_ratio", (DL_FUNC) &_INLAvaan_cpp_mills_ratio, 1},
    {"_INLAvaan_cpp_dsnorm", (DL_FUNC) &_INLAvaan_cpp_dsnorm, 6},
    {"_INLAvaan_cpp_fit_skew_normal_objective", (DL_FUNC) &_INLAvaan_cpp_fit_skew_normal_objective, 6},
    {"_INLAvaan_cpp_fit_skew_normal_gradient", (DL_FUNC) &_INLAvaan_cpp_fit_skew_normal_gradient, 6},
    {"_INLAvaan_cpp_fit_skew_normal_hessian", (DL_FUNC) &_INLAvaan_cpp_fit_skew_normal_hessian, 5},
    {"_INLAvaan_cpp_fit_skew_normal_optimize", (DL_FUNC) &_INLAvaan_cpp_fit_skew_normal_optimize, 11},
    {"_INLAvaan_cpp_fit_skew_normal_sample_nll", (DL_FUNC) &_INLAvaan_cpp_fit_skew_normal_sample_nll, 2},
    {"_INLAvaan_cpp_fit_skew_normal_sample_optimize", (DL_FUNC) &_INLAvaan_cpp_fit_skew_normal_sample_optimize, 7},
    {"_INLAvaan_cpp_fast_grad", (DL_FUNC) &_INLAvaan_cpp_fast_grad, 3},
    {"_INLAvaan_cpp_fast_jacobian", (DL_FUNC) &_INLAvaan_cpp_fast_jacobian, 3},
    {"_INLAvaan_cpp_fast_hessian", (DL_FUNC) &_INLAvaan_cpp_fast_hessian, 3},
    {"_INLAvaan_cpp_lisrel_implied_cov", (DL_FUNC) &_INLAvaan_cpp_lisrel_implied_cov, 2},
    {"_INLAvaan_cpp_lisrel_implied_mean", (DL_FUNC) &_INLAvaan_cpp_lisrel_implied_mean, 2},
    {"_INLAvaan_cpp_lisrel_latent_posterior", (DL_FUNC) &_INLAvaan_cpp_lisrel_latent_posterior, 2},
    {"_INLAvaan_cpp_lisrel_predict_y", (DL_FUNC) &_INLAvaan_cpp_lisrel_predict_y, 3},
    {"_INLAvaan_cpp_lisrel_impute_missing", (DL_FUNC) &_INLAvaan_cpp_lisrel_impute_missing, 2},
    {"_INLAvaan_cpp_lisrel_loglik_and_grad", (DL_FUNC) &_INLAvaan_cpp_lisrel_loglik_and_grad, 2},
    {"_INLAvaan_cpp_lisrel_loglik", (DL_FUNC) &_INLAvaan_cpp_lisrel_loglik, 2},
    {"_INLAvaan_cpp_lisrel_grad", (DL_FUNC) &_INLAvaan_cpp_lisrel_grad, 2},
    {"_INLAvaan_cpp_lisrel_hessian_theta", (DL_FUNC) &_INLAvaan_cpp_lisrel_hessian_theta, 6},
    {"_INLAvaan_cpp_lisrel_twolevel_implied_blocks", (DL_FUNC) &_INLAvaan_cpp_lisrel_twolevel_implied_blocks, 2},
    {"_INLAvaan_cpp_marginals_batch", (DL_FUNC) &_INLAvaan_cpp_marginals_batch, 12},
    {"_INLAvaan_cpp_lisrel_optimize", (DL_FUNC) &_INLAvaan_cpp_lisrel_optimize, 8},
    {"_INLAvaan_cpp_norta_adjust", (DL_FUNC) &_INLAvaan_cpp_norta_adjust, 10},
    {"_INLAvaan_cpp_sample_batch", (DL_FUNC) &_INLAvaan_cpp_sample_batch, 10},
    {"_INLAvaan_cpp_prior_logdens_scan", (DL_FUNC) &_INLAvaan_cpp_prior_logdens_scan, 11},
    {"_INLAvaan_cpp_prior_logdens_vec", (DL_FUNC) &_INLAvaan_cpp_prior_logdens_vec, 9},
    {"_INLAvaan_cpp_vb_fg", (DL_FUNC) &_INLAvaan_cpp_vb_fg, 17},
    {NULL, NULL, 0}
};

RcppExport void R_init_INLAvaan(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
