lavaan___lav_mvnorm_loglik_samplestats <-
  utils::getFromNamespace("lav_mvnorm_loglik_samplestats", "lavaan")
lavaan___lav_model_gradient <-
  utils::getFromNamespace("lav_model_gradient", "lavaan")
lavaan___lav_model_objective_pml <-
  utils::getFromNamespace("lav_model_objective_pml", "lavaan")
lavaan___lav_model_vcov <-
  utils::getFromNamespace("lav_model_vcov", "lavaan")
lavaan___lav_model_loglik <-
  utils::getFromNamespace("lav_model_loglik", "lavaan")
lavaan___lav_model_objective <-
  utils::getFromNamespace("lav_model_objective", "lavaan")
