#' Simulate Datasets from the Generative Model
#'
#' Generate complete synthetic datasets from a fitted INLAvaan model. For each
#' simulation, a single parameter vector is drawn (from the posterior or prior),
#' and then `sample.nobs` observations are generated from the model-implied
#' distribution at that parameter value.
#'
#' @details
#' This function is designed for tasks that require **full replicate datasets**
#' from a single parameter draw, such as simulation-based calibration (SBC) and
#' posterior predictive p-values. It differs from [sampling()] which generates
#' one observation per parameter draw (useful for prior/posterior predictive
#' density overlays).
#'
#' For each simulation \eqn{s = 1, \ldots, S}:
#' 1. Draw \eqn{\boldsymbol\theta^{(s)}} from the posterior (or prior).
#' 2. Compute the model-implied covariance
#'    \eqn{\boldsymbol\Sigma(\boldsymbol\theta^{(s)})}.
#'    If it is not positive-definite, reject and redraw.
#' 3. Generate a dataset of `sample.nobs` rows from
#'    \eqn{N(\boldsymbol\mu(\boldsymbol\theta^{(s)}),\,
#'    \boldsymbol\Sigma(\boldsymbol\theta^{(s)}))}.
#'
#' Parameter draws reuse the same internal machinery as [sampling()]
#' (`sample_params_prior` / `sample_params_posterior`), so the prior
#' specification is consistent.
#'
#' @param object An object of class [INLAvaan].
#' @param nsim Number of replicate datasets to generate (default 1).
#' @param seed Optional random seed (passed to [set.seed()]).
#' @param sample.nobs Number of observations per dataset, per group for
#'   multigroup models (a single number is used for every group). Defaults to
#'   the sample size of the original data.
#' @param prior Logical. When `TRUE`, parameters are drawn from the prior;
#'   when `FALSE` (default), from the posterior.
#' @param samp_copula Logical. When `TRUE` (default) and `prior = FALSE`,
#'   posterior parameter draws use the copula method. Ignored when
#'   `prior = TRUE`.
#' @param silent Logical. When `TRUE`, suppresses the informational message
#'   about rejected non-PD draws. Default `FALSE`.
#' @param ... Additional arguments (currently unused).
#'
#' @returns A list of length `nsim`. Each element is a data frame with
#'   `sample.nobs` rows and two attributes:
#'   * `"truth"` — named numeric vector of lavaan-side (x-space, constrained)
#'     parameter values used to generate the dataset.
#'   * `"truth_theta"` — named numeric vector of the corresponding unconstrained
#'     (theta-space) parameter values.
#'
#' @seealso [sampling()] for single-observation draws from the predictive
#'   distribution (prior/posterior predictive checks).
#'
#' @example inst/examples/ex-simulate.R
#' @importFrom stats simulate rgamma
#' @name simulate
#' @rdname simulate
#' @aliases simulate,INLAvaan-method
#' @export
setMethod(
  "simulate",
  "INLAvaan",
  function(
    object,
    nsim = 1L,
    seed = NULL,
    sample.nobs = NULL,
    prior = FALSE,
    samp_copula = TRUE,
    silent = FALSE,
    ...
  ) {
    if (!is.null(seed)) {
      set.seed(seed)
    }
    nsim <- as.integer(nsim)

    int <- object@external$inlavaan_internal
    pt <- int$partable
    lavmodel <- int$lavmodel

    if (has_random_slopes(lavmodel)) {
      cli_abort(
        c(
          "{.fn simulate} cannot generate data from a random-slope model.",
          "x" = "The data are generated by {.fn lavaan::simulateData}, which
                 refuses a parameter table carrying {.code rv()} modifiers:
                 lavaan has no random-slope data generator.",
          "i" = "Generate the clusters yourself from the posterior draws of
                 the slope."
        ),
        class = "inlavaan_rs_simulate"
      )
    }

    xnames <- pt$names[pt$free > 0 & !duplicated(pt$free)]
    # A two-level fit keeps its own cluster design unless a sample size is
    # given. Without a cluster index lavaan invents a balanced one. lavaan's
    # multilevel generator also warns on every call unless `mass = TRUE`.
    sim_ml_args <- list()
    if (int$lavdata@nlevels > 1L) {
      sim_ml_args$mass <- TRUE
      if (is.null(sample.nobs)) {
        cl_idx <- lapply(int$lavdata@Lp, function(lp) lp$cluster.idx[[2L]])
        sim_ml_args$cluster_idx <- if (length(cl_idx) == 1L) {
          cl_idx[[1L]]
        } else {
          cl_idx
        }
      }
    }
    # One sample size per group, as lavaan::simulateData() needs
    n <- if (is.null(sample.nobs)) {
      unlist(object@SampleStats@nobs)
    } else {
      rep_len(sample.nobs, lavmodel@ngroups)
    }

    # Draw a generous batch of parameters upfront
    oversample <- nsim * 5L
    if (isTRUE(prior)) {
      samp <- sample_params_prior(int, oversample)
    } else {
      samp <- sample_params_posterior(int, oversample, samp_copula)
    }
    colnames(samp$x_samp) <- xnames
    colnames(samp$theta_samp) <- xnames

    results <- vector("list", nsim)
    collected <- 0L
    idx <- 0L # index into pre-drawn batch
    max_attempts <- nsim * 20L
    attempts <- 0L

    while (collected < nsim && attempts < max_attempts) {
      idx <- idx + 1L
      attempts <- attempts + 1L

      # Refill batch if exhausted
      if (idx > nrow(samp$x_samp)) {
        # nocov start
        if (isTRUE(prior)) {
          samp <- sample_params_prior(int, oversample)
        } else {
          samp <- sample_params_posterior(int, oversample, samp_copula)
        }
        colnames(samp$x_samp) <- xnames
        colnames(samp$theta_samp) <- xnames
        idx <- 1L
      } # nocov end

      x_draw <- samp$x_samp[idx, ]
      theta_draw <- samp$theta_samp[idx, ]

      # Check PD of model-implied covariance
      lavmodel_x <- lavaan::lav_model_set_parameters(
        lavmodel,
        as.numeric(x_draw)
      )
      implied <- lavaan::lav_model_implied(lavmodel_x)

      all_pd <- TRUE
      for (b in seq_len(lavmodel@nblocks)) {
        eigs <- eigen(
          implied_block_moments(implied, b, lavmodel, int$lavsamplestats)$cov,
          symmetric = TRUE,
          only.values = TRUE
        )$values
        if (any(eigs < 1e-10)) {
          all_pd <- FALSE
          break
        }
      }
      if (!all_pd) {
        next
      }

      # Generate data via lavaan's simulateData using the partable
      pt_sim <- lavaan::lav_partable_complete(lavaan::partable(object))
      # x_draw holds one value per free index, shared by equal parameters
      pt_sim$est[pt_sim$free > 0] <- as.numeric(x_draw)[
        pt_sim$free[pt_sim$free > 0]
      ]
      # simulateData() fails on a conditional.x partable. Without the exo flags
      # it draws the covariates from their fixed moments, as for other fits.
      if (isTRUE(lavmodel@conditional.x)) {
        pt_sim$exo[] <- 0L
      }

      # The := rows play no part in the data, so a draw where one is undefined
      # is fine.
      dat <- tryCatch(
        muffle_nan_warnings(do.call(
          lavaan::simulateData,
          c(list(pt_sim, sample.nobs = n), sim_ml_args)
        )),
        error = function(e) NULL
      )
      if (is.null(dat)) {
        # nocov
        next
      }

      # Without a mean structure lavaan::simulateData() centres the columns at
      # zero (there are no intercepts in the partable). INLAvaan integrates the
      # saturated means out under a flat prior, so the posterior of the mean is
      # N(ybar, Sigma / n). Draw one such mean vector for this replicate (all
      # its rows share the same theta, hence the same mean) and shift the data
      # onto the observed scale, mirroring sampling(type = "observed").
      if (
        !isTRUE(lavmodel@meanstructure) &&
          !isTRUE(prior) &&
          lavmodel@ngroups == 1L
      ) {
        ybar <- colMeans(int$lavdata@X[[1L]], na.rm = TRUE)
        names(ybar) <- int$lavdata@ov.names[[1L]]
        mu <- ybar
        if (marginalised_means_active(lavmodel)) {
          shift <- draw_marginalised_mean_shift(
            implied$cov[[1L]],
            int$lavsamplestats@x.idx[[1L]],
            nrow(int$lavdata@X[[1L]])
          )
          if (!is.null(shift)) {
            mu <- ybar + shift
          }
        }
        for (v in intersect(names(mu), colnames(dat))) {
          if (is.numeric(dat[[v]])) {
            dat[[v]] <- dat[[v]] + mu[[v]]
          }
        }
      }

      collected <- collected + 1L
      attr(dat, "truth") <- x_draw
      attr(dat, "truth_theta") <- theta_draw
      results[[collected]] <- dat
    }

    rejected <- attempts - collected
    if (rejected > 0L && !isTRUE(silent)) {
      # nocov start
      rej_pct <- round(100 * rejected / attempts, 1)
      cli_inform(
        "simulate: {rejected} of {attempts} draw{?s} ({rej_pct}%) rejected (non-PD model-implied covariance)."
      )
    } # nocov end

    if (collected < nsim) {
      # nocov start
      cli_warn(c(
        "Rejection sampling fell short of the requested {nsim} simulations.",
        "i" = "Only {collected} of {nsim} obtained after {attempts} attempts.",
        "i" = "Consider using more informative priors."
      ))
      if (collected == 0L) {
        cli_abort("No valid draws obtained. Priors may be too vague.")
      }
      results <- results[seq_len(collected)]
    } # nocov end

    results
  }
)
