# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_mills_ratio <- function(u) {
    .Call(`_INLAvaan_cpp_mills_ratio`, u)
}

cpp_dsnorm <- function(x, xi, omega, alpha, logC = 0.0, log_out = FALSE) {
    .Call(`_INLAvaan_cpp_dsnorm`, x, xi, omega, alpha, logC, log_out)
}

cpp_fit_skew_normal_objective <- function(param, x, y, threshold_log_drop, is_est_k, temp) {
    .Call(`_INLAvaan_cpp_fit_skew_normal_objective`, param, x, y, threshold_log_drop, is_est_k, temp)
}

cpp_fit_skew_normal_gradient <- function(param, x, y, threshold_log_drop, is_est_k, temp) {
    .Call(`_INLAvaan_cpp_fit_skew_normal_gradient`, param, x, y, threshold_log_drop, is_est_k, temp)
}

cpp_fit_skew_normal_hessian <- function(param, x, y, threshold_log_drop, temp) {
    .Call(`_INLAvaan_cpp_fit_skew_normal_hessian`, param, x, y, threshold_log_drop, temp)
}

cpp_fit_skew_normal_optimize <- function(par0, x, y, threshold_log_drop, is_est_k, temp, max_iter = 200L, grad_tol = 1e-8, m_bfgs = 10L, max_ls = 40L, h = 1e-5) {
    .Call(`_INLAvaan_cpp_fit_skew_normal_optimize`, par0, x, y, threshold_log_drop, is_est_k, temp, max_iter, grad_tol, m_bfgs, max_ls, h)
}

cpp_fit_skew_normal_sample_nll <- function(par, x) {
    .Call(`_INLAvaan_cpp_fit_skew_normal_sample_nll`, par, x)
}

cpp_fit_skew_normal_sample_optimize <- function(par0, x, max_iter = 200L, grad_tol = 1e-8, m_bfgs = 10L, max_ls = 40L, h = 1e-5) {
    .Call(`_INLAvaan_cpp_fit_skew_normal_sample_optimize`, par0, x, max_iter, grad_tol, m_bfgs, max_ls, h)
}

cpp_fast_grad <- function(fn, x, h = 1e-5) {
    .Call(`_INLAvaan_cpp_fast_grad`, fn, x, h)
}

cpp_fast_jacobian <- function(gr_fn, x, h = 1e-5) {
    .Call(`_INLAvaan_cpp_fast_jacobian`, gr_fn, x, h)
}

cpp_fast_hessian <- function(fn, x, h = 1e-5) {
    .Call(`_INLAvaan_cpp_fast_hessian`, fn, x, h)
}

cpp_lisrel_implied_cov <- function(model, x_free) {
    .Call(`_INLAvaan_cpp_lisrel_implied_cov`, model, x_free)
}

cpp_lisrel_implied_mean <- function(model, x_free) {
    .Call(`_INLAvaan_cpp_lisrel_implied_mean`, model, x_free)
}

cpp_lisrel_latent_posterior <- function(model, x_free) {
    .Call(`_INLAvaan_cpp_lisrel_latent_posterior`, model, x_free)
}

cpp_lisrel_predict_y <- function(model, x_free, add_noise = FALSE) {
    .Call(`_INLAvaan_cpp_lisrel_predict_y`, model, x_free, add_noise)
}

cpp_lisrel_impute_missing <- function(model, x_free) {
    .Call(`_INLAvaan_cpp_lisrel_impute_missing`, model, x_free)
}

cpp_lisrel_loglik_and_grad <- function(model, x_free) {
    .Call(`_INLAvaan_cpp_lisrel_loglik_and_grad`, model, x_free)
}

cpp_lisrel_loglik <- function(model, x_free) {
    .Call(`_INLAvaan_cpp_lisrel_loglik`, model, x_free)
}

cpp_lisrel_grad <- function(model, x_free) {
    .Call(`_INLAvaan_cpp_lisrel_grad`, model, x_free)
}

cpp_lisrel_hessian_theta <- function(model, par, transforms, cov_var_idx1, cov_var_idx2, h_hess = 1e-5) {
    .Call(`_INLAvaan_cpp_lisrel_hessian_theta`, model, par, transforms, cov_var_idx1, cov_var_idx2, h_hess)
}

cpp_lisrel_twolevel_implied_blocks <- function(model, x_free) {
    .Call(`_INLAvaan_cpp_lisrel_twolevel_implied_blocks`, model, x_free)
}

cpp_marginals_batch <- function(model, theta_star, Vscan, L_chol, transforms, z_grid, cov_var_idx1, cov_var_idx2, H_prior_neg, delta_outer = 0.01, h_inner = 1e-5, nthreads = 1L) {
    .Call(`_INLAvaan_cpp_marginals_batch`, model, theta_star, Vscan, L_chol, transforms, z_grid, cov_var_idx1, cov_var_idx2, H_prior_neg, delta_outer, h_inner, nthreads)
}

cpp_lisrel_optimize <- function(model, par0, transforms, max_iter = 200L, grad_tol = 1e-8, m_bfgs = 10L, max_ls = 40L, h = 1e-5) {
    .Call(`_INLAvaan_cpp_lisrel_optimize`, model, par0, transforms, max_iter, grad_tol, m_bfgs, max_ls, h)
}

cpp_norta_adjust <- function(z1, ww_flat, q1_all, R_in, mu_sn, sd_sn, alphas, u_grid, q_grids, nthreads = 1L) {
    .Call(`_INLAvaan_cpp_norta_adjust`, z1, ww_flat, q1_all, R_in, mu_sn, sd_sn, alphas, u_grid, q_grids, nthreads)
}

cpp_sample_batch <- function(z_raw, R_chol_ut, sn_xi, sn_omega, sn_alpha, transforms, cov_var_idx1, cov_var_idx2, nthreads = 1L, n_grid = 2000L) {
    .Call(`_INLAvaan_cpp_sample_batch`, z_raw, R_chol_ut, sn_xi, sn_omega, sn_alpha, transforms, cov_var_idx1, cov_var_idx2, nthreads, n_grid)
}

cpp_prior_logdens_scan <- function(theta_star, Vscan, z_grid, free_id, trans_type, prior_type, p1, p2, is_sd_prior, is_prec_prior, nthreads = 1L) {
    .Call(`_INLAvaan_cpp_prior_logdens_scan`, theta_star, Vscan, z_grid, free_id, trans_type, prior_type, p1, p2, is_sd_prior, is_prec_prior, nthreads)
}

cpp_prior_logdens_vec <- function(theta_mat, free_id, trans_type, prior_type, p1, p2, is_sd_prior, is_prec_prior, nthreads = 1L) {
    .Call(`_INLAvaan_cpp_prior_logdens_vec`, theta_mat, free_id, trans_type, prior_type, p1, p2, is_sd_prior, is_prec_prior, nthreads)
}

cpp_vb_fg <- function(delta, mu0, L, Z, model, transforms, cov_var_idx1, cov_var_idx2, prior_free_id, prior_trans, prior_type, prior_p1, prior_p2, prior_is_sd, prior_is_prec, ceq_K, nthreads = 1L) {
    .Call(`_INLAvaan_cpp_vb_fg`, delta, mu0, L, Z, model, transforms, cov_var_idx1, cov_var_idx2, prior_free_id, prior_trans, prior_type, prior_p1, prior_p2, prior_is_sd, prior_is_prec, ceq_K, nthreads)
}

